spring.application.name=kb-fashion-house
# SERVER PORT
server.port=8181

# DATABASE CONFIG (MySQL)
spring.datasource.url=jdbc:mysql://18.61.201.191:3306/fashion_db
spring.datasource.username=root
spring.datasource.password=root123

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL DRIVER
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
